# Generated by Django 5.0.2 on 2024-04-03 06:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "host",
                    models.CharField(default="http://127.0.0.1:8000/", max_length=255),
                ),
                ("display_name", models.CharField(max_length=100)),
                (
                    "profile_image",
                    models.ImageField(default="default.jpg", upload_to="profile_pics"),
                ),
                ("github", models.CharField(blank=True, max_length=100)),
                ("date_joined", models.DateTimeField(auto_now_add=True, null=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("is_remote", models.BooleanField(default=False)),
                (
                    "followers",
                    models.ManyToManyField(
                        blank=True, related_name="following", to="lostapp.author"
                    ),
                ),
                (
                    "follows",
                    models.ManyToManyField(
                        blank=True, related_name="followed_by", to="lostapp.author"
                    ),
                ),
                (
                    "pending_follow_requests",
                    models.ManyToManyField(
                        blank=True,
                        related_name="pending_followers",
                        to="lostapp.author",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lostapp.node",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "contentType",
                    models.CharField(default="text/markdown", max_length=100),
                ),
                ("published", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lostapp.author"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Post"),
                            (2, "Comment"),
                            (3, "Follow"),
                            (4, "Like"),
                        ]
                    ),
                ),
                ("item", models.UUIDField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lostapp.author"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("source", models.CharField(blank=True, max_length=255)),
                ("origin", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "content_format",
                    models.IntegerField(
                        choices=[(1, "Plain Text"), (2, "Markdown"), (3, "Image")],
                        default=1,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "date_posted",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "visibility",
                    models.IntegerField(
                        choices=[(1, "Public"), (2, "Unlisted"), (3, "Friends")],
                        default=1,
                    ),
                ),
                ("is_remote", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="lostapp.author",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lostapp.author"
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="lostapp.comment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="lostapp.post",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="lostapp.post",
            ),
        ),
    ]
